language: php

php:
  - 5.5
  - 5.6

branches:
  except:
    - gh-pages

addons:
  hosts:
    - delboy1978k

sudo: false

services:
  - mysql


install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta2"
  - composer install


before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - mysql -e "create database IF NOT EXISTS delboy1978uk;\nUSE mysql;\nGRANT ALL PRIVILEGES ON *.* TO dbuser@"%" IDENTIFIED BY '[123456]';\nFLUSH PRIVILEGES;\n" -uroot
script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
