language: php

php:
  - 5.5
  - 5.6

branches:
  except:
    - gh-pages

addons:
  hosts:
    - delboy1978k

sudo: false

services:
  - mysql


install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer global require "fxp/composer-asset-plugin:1.0.0-beta2"
  - composer install


before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - mysql -e "create database IF NOT EXISTS delboy1978uk;\n" -uroot
  - mysql -e "USE mysql;\n" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO dbuser@'%' IDENTIFIED BY '[123456]';\n" -uroot
  - mysql -e "FLUSH PRIVILEGES;\n" -uroot
  - mysql -e "USE delboy1978uk;\n" -uroot
  - mysql -e "CREATE TABLE `person` (`id` int(11) NOT NULL AUTO_INCREMENT,`country` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,`firstname` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,`middlename` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,`lastname` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,`aka` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,`dob` date DEFAULT NULL,`birthplace` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,PRIMARY KEY (`id`),KEY `IDX_38D5CE435373C966` (`country`)) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;" -uroot
script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
